;;; naquadah-theme.el --- A color theme

;; Copyright (C) 2011 Julien Danjou

;; Authors: Julien Danjou <julien@danjou.info>

;; This file is NOT part of GNU Emacs.

;; GNU Emacs is free software: you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation, either version 3 of the License, or
;; (at your option) any later version.

;; GNU Emacs is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <http://www.gnu.org/licenses/>.

(require 'color-theme)

;;;###autoload
(defun color-theme-naquadah ()
  (interactive)
  (color-theme-install
   '(color-theme-naquadah
     ((background-color . "#252A2B")
      (background-mode . dark)
      (border-color . "black")
      (cursor-color . "#aa0000")
      (foreground-color . "#eeeeec")
      (mouse-color . "sienna1"))
     (anything-header ((t (:bold t :background "gray15" :foreground "#edd400"))))
     (blue ((t (:foreground "#374EAB"))))
     (bold ((t (:bold t :underline nil :background nil))))
     (comint-highlight-input ((t (:italic t :bold t))))
     (comint-highlight-prompt ((t (:foreground "#89E234"))))
     (cursor ((t (:background "#aa0000"))))
     (custom-button  ((t (:box (:line-width 1 :style released-button) :background "gray50" :foreground "black"))))
     (custom-button-mouse  ((t (:inherit custom-button :background "gray60"))))
     (custom-button-mouse-pressed-unraised  ((t (:inherit custom-button-unraised :background "gray60"))))
     (custom-button-mouse-unraised  ((t (:inherit custom-button-unraised :background "gray60"))))
     (custom-button-pressed  ((t (:inherit custom-button :box (:style pressed-button)))))
     (custom-button-unraised  ((t (:background "gray50" :foreground "black"))))
     (custom-documentation ((t (:italic t))))
     (custom-face-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
     (custom-group-tag ((t (:bold t :foreground "#FFA500" :height 1.3))))
     (custom-link ((t (:inherit link))))
     (custom-state-face ((t (:foreground "#72A0CF"))))
     (custom-variable-button ((t (:inherit 'custom-button))))
     (custom-variable-tag ((t (:bold t :foreground "#edd400" :height 1.1))))
     (default ((((min-colors 4096)) (:background "#252A2B" :foreground "#eeeeec"))))
     (diff-added ((t (:foreground "#89E234"))))
     (diff-changed ((t (:foreground "#FFA500"))))
     (diff-file-header ((t (:background nil :foreground "white"))))
     (diff-function ((t (:foreground "#FFA500"))))
     (diff-header ((t (:background "grey10"))))
     (diff-hunk-header ((t (:bold t))))
     (diff-removed ((t (:foreground "#8A0B0B"))))
     (egocentric-face ((t (:foreground "#ff4289" :weight bold))))
     (erc-current-nick-face ((t (:inherit egocentric-face :weight thin :foreground nil))))
     (erc-direct-msg-face ((t (:foreground "#ee5577"))))
     (erc-fool-face ((t (:foreground "gray60" :weight thin))))
     (erc-header-line ((t (:background "black" :foreground "white"))))
     (erc-input-face ((t (:foreground "gray70"))))
     (erc-my-nick-face ((t (:inherit egocentric-face :weight thin :foreground nil))))
     (erc-notice-face ((t (:foreground "light blue" :weight thin))))
     (erc-pal-face ((t (:foreground "DarkOliveGreen3" :weight bold))))
     (erc-prompt-face ((t (:background "black" :foreground "gray80" :weight bold))))
     (erc-timestamp-face ((t (:foreground "gray70" :weight bold))))
     (font-lock-comment-face ((t (:foreground "#888a85" :italic t))))
     (font-lock-builtin-face ((t (:foreground "#72A0CF"))))
     (font-lock-constant-face ((t (:foreground "#89E234"))))
     (font-lock-comment-delimiter-face ((t (:inherit font-lock-comment-face))))
     (font-lock-doc-face ((t (:foreground "#888a85"))))
     (font-lock-function-name-face ((t (:foreground "#FCCD3A" :bold t))))
     (font-lock-keyword-face ((t (:inherit font-lock-builtin-face :bold t))))
     (font-lock-string-face ((t (:foreground "#C66CD0"))))
     (font-lock-type-face ((t (:inherit font-lock-constant-face :bold t))))
     (font-lock-variable-name-face ((t (:foreground "#FC683A"))))
     (font-lock-warning-face ((t (:bold t :foreground "#FFA500"))))
     (fringe ((t (:background "gray10"))))
     (git-commit-branch-face ((t (:foreground "#FFA500" :bold t))))
     (git-commit-comment-face ((t (:inherit font-lock-comment-face))))
     (git-commit-known-pseudo-header-face ((t (:bold t :foreground "#729fcf"))))
     (git-commit-nonempty-second-line-face ((t (:foreground "red"))))
     (git-commit-pseudo-header-face ((t (:italic t :foreground "#8ae234"))))
     (git-commit-summary-face ((t (:bold t))))
     (gnus-cite-face-1 ((t (:foreground "#ad7fa3"))))
     (gnus-cite-face-2 ((t (:foreground "sienna3"))))
     (gnus-cite-face-3 ((t (:foreground "khaki4"))))
     (gnus-cite-face-4 ((t (:foreground "PaleTurquoise4"))))
     (gnus-header-content ((t (:italic t :foreground "#8ae234"))))
     (gnus-header-from ((t (:bold t :foreground "#e0d400"))))
     (gnus-header-name-face ((t (:bold t :foreground "#729fcf"))))
     (gnus-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3"))))
     (gnus-header-subject ((t (:foreground "#e0d400"))))
     (gnus-signature-face ((t (:italic t :foreground "OliveDrab1"))))
     (gnus-summary-normal-ancient-face ((t (:foreground "medium sea green"))))
     (gnus-summary-normal-read-face ((t (:foreground "lime green"))))
     (gnus-summary-normal-ticked-face ((t (:foreground "#FC683A"))))
     (gnus-summary-normal-unread-face ((t (:foreground "white"))))
     (gnus-summary-cancelled-face ((t (:background "black" :foreground "#FCCD3A"))))
     (gnus-summary-high-ancient-face ((t (:inherit gnus-summary-normal-ancient-face))))
     (gnus-summary-high-read-face ((t (:inherit gnus-summary-normal-read-face))))
     (gnus-summary-high-ticked-face ((t (:inherit gnus-summary-normal-ticked-face))))
     (gnus-summary-high-unread-face ((t (:inherit gnus-summary-normal-unread-face))))
     (gnus-summary-low-ancient-face ((t (:inherit gnus-summary-normal-ancient-face) :italic t)))
     (gnus-summary-low-read-face ((t (:inherit gnus-summary-normal-read-face :italic t))))
     (gnus-summary-low-ticked-face ((t (:inherit gnus-summary-normal-ticked-face :italic t))))
     (gnus-summary-low-unread-face ((t (:inherit gnus-summary-normal-unread-face :italic t))))
     (gnus-summary-selected ((t (:background "#72A0CF" :foreground "white"))))
     (header-line ((t (:foreground "#dddddd" :background "#1e2426" :box (:line-width 1 :color "#444444")))))
     (highlight ((t (:background "brown1" :foreground nil))))
     (hl-line ((t (:background "#191919"))))
     (ido-subdir ((t (:foreground "orange1"))))
     (info-xref ((t (:foreground "#72A0CF"))))
     (info-xref-visited ((t (:foreground "#C66CD0"))))
     (isearch ((t (:background "#FFA500" :foreground "#252A2B"))))
     (italic ((t (:italic t :underline nil :background nil))))
     (link ((t (:underline t :foreground "#72A0CF"))))
     (match ((t (:bold t :background "#e9b96e" :foreground "#2e3436"))))
     (message-header-cc ((t (:foreground "white"))))
     (message-header-name-face ((t (:foreground "#729cfc"))))
     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "LightSkyBlue3"))))
     (message-header-other-face ((t (:foreground "LightSkyBlue3"))))
     (message-header-subject ((t (:foreground "white"))))
     (message-header-to ((t (:foreground "white"))))
     (message-header-xheader-face ((t (:foreground "DodgerBlue3"))))
     (minibuffer-prompt ((t (:foreground "#72A0CF" :bold t))))
     (mm-uu-extract ((t (:background "#404040"))))
     (mode-line ((t (:foreground "#fafafa" :background "#000000" :box (:line-width 1 :color "#444444")))))
     (mode-line-buffer-id ((t (:bold t :foreground "#FFA500"))))
     (mode-line-inactive ((t (:foreground "#888888" :background "#2c2f2f" :box (:line-width 1 :color "black")))))
     (org-agenda-date ((t (:underline nil :foreground "SkyBlue2" :height 1.2))))
     (org-agenda-date-telecommuting ((t (:inherit org-agenda-date :foreground "#ffbb22" :weight bold))))
     (org-agenda-date-today ((t (:inherit org-agenda-date :foreground "#edd466" :weight bold))))
     (org-agenda-date-weekend ((t (:inherit org-agenda-date :foreground "brown3" :weight bold))))
     (org-block ((t (:foreground "#bbbbbc"))))
     (org-date ((t (:underline nil :foreground "#edd466" :background nil))))
     (org-done ((t (:bold t :foreground "forest green"))))
     (org-footnote  ((t (:underline t :foreground "magenta3"))))
     (org-hide ((t (:foreground "#252a2b"))))
     (org-level-1 ((t (:bold t :foreground "#4788cc" :height 1.2))))
     (org-level-2 ((t (:bold t :foreground "#6ac214" :height 1.1))))
     (org-level-3 ((t (:bold t :foreground "#edd400" :height 1.0))))
     (org-level-4 ((t (:bold t :foreground "tomato" :height 1.0))))
     (org-link ((t (:foreground "SkyBlue2"))))
     (org-mode-line-clock ((t (:foreground "#cc77ff" :background nil))))
     (org-quote ((t (:inherit org-block :slant italic))))
     (org-special-keyword ((t (:foreground "brown1"))))
     (org-todo ((t (:bold t :foreground "#ff2020"))))
     (org-verbatim ((t (:foreground "#eeeeec" :underline t :slant italic))))
     (org-verse ((t (:inherit org-block :slant italic))))
     (region ((t (:background "grey30"))))
     (rst-level-1-face ((t (:inherit org-level-1 :background nil))))
     (rst-level-2-face ((t (:inherit org-level-2 :background nil))))
     (rst-level-3-face ((t (:inherit org-level-3 :background nil))))
     (rst-level-4-face ((t (:inherit org-level-4 :background nil))))
     (show-paren-match-face ((t (:background "#89E234"))))
     (show-paren-mismatch-face ((t (:background "#C66CD0"))))
     (spam-face ((t (:background "black" :foreground "magenta3"))))
     (tooltip ((t (:inherit variable-pitch :foreground "LightYellow" :background "black"))))
     (which-func ((t (:foreground "#729cfc"))))
     (widget-button ((t (:bold t))))
     (widget-field ((t (:foreground "#FFA500" :background "gray30"))))
     (widget-mouse-face ((t (:bold t :foreground "white" :background "#8A0B0B"))))
     (widget-single-line-field ((t (:foreground "#FFA500" :background "gray30")))))))

